const express = require('express');
const { protect, authorize } = require('../middleware/auth');
const { ROLES } = require('../constants/roles');
const controller = require('../controllers/salesSheetController');

const router = express.Router();
router.use(protect, authorize(ROLES.ADMIN, ROLES.SALES_TEAM, ROLES.RECEPTIONIST));
router.get('/columns', controller.listColumns);
router.post('/columns', authorize(ROLES.ADMIN), controller.createColumn);
router.patch('/columns/:id', authorize(ROLES.ADMIN), controller.updateColumn);
router.delete('/columns/:id', authorize(ROLES.ADMIN), controller.deleteColumn);
router.get('/appointments', controller.listAppointments);
router.get('/management', authorize(ROLES.ADMIN, ROLES.RECEPTIONIST), controller.listManagedAppointments);
router.get('/management-columns', authorize(ROLES.ADMIN, ROLES.RECEPTIONIST), controller.listManagementColumns);
router.post('/management-columns', authorize(ROLES.ADMIN), controller.createManagementColumn);
router.patch('/management-columns/:id', authorize(ROLES.ADMIN), controller.updateManagementColumn);
router.delete('/management-columns/:id', authorize(ROLES.ADMIN), controller.deleteManagementColumn);
router.post('/management', authorize(ROLES.ADMIN, ROLES.RECEPTIONIST), controller.createManagedAppointment);
router.patch('/management/:id', authorize(ROLES.ADMIN, ROLES.RECEPTIONIST), controller.updateManagedAppointment);
router.delete('/management/:id', authorize(ROLES.ADMIN, ROLES.RECEPTIONIST), controller.deleteManagedAppointment);
router.post('/appointments', controller.createAppointment);
router.post('/appointments/:id/accept', authorize(ROLES.ADMIN, ROLES.RECEPTIONIST), controller.acceptAppointment);
router.patch('/appointments/:id', controller.updateAppointment);
router.delete('/appointments/:id', controller.deleteAppointment);
module.exports = router;
