export const PATIENT_CATEGORIES = {
  AUTISM_ADHD: 'autism_adhd',
  MENTAL_HEALTH: 'mental_health',
};

export const ALL_PATIENT_CATEGORIES = [PATIENT_CATEGORIES.AUTISM_ADHD, PATIENT_CATEGORIES.MENTAL_HEALTH];

export const CATEGORY_LABELS = {
  [PATIENT_CATEGORIES.AUTISM_ADHD]: 'Autism/ADHD',
  [PATIENT_CATEGORIES.MENTAL_HEALTH]: 'Mental Health',
};